[[module.imports]]
path = "github.com/hbstack/blog"

[[module.imports]]
path = "github.com/hbstack/socials"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hugopress.modules.hb-blog-sidebar-profile.hooks.hb-blog-sidebar]
cacheable = true
weight = 1

[params.hb.blog.sidebar.profile]
avatar = "/images/logo.png"
avatar_size = 100
title = "" # default to site title.
description = "" # default to site description.
company = ""
location = ""
